[package]
name = "precompile-utils-macro-v2"
version = "0.1.1"
description = "Procedural macros for precompile-utils v2"
edition = "2021"
license = "Unlicense"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/tests.rs"

[dependencies]
case = "1.0"
num_enum = { workspace = true }
prettyplease = "0.2.12"
proc-macro2 = "1.0"
quote = "1.0"
sp-core-hashing = { workspace = true }
syn = { version = "1.0", features = ["extra-traits", "fold", "full", "visit"] }

[dev-dependencies]
macrotest = "1.0.9"
trybuild = "1.0"

# Dev-only deps needed by the test suite
fp-evm = { workspace = true }
frame-support = { workspace = true }
sp-std = { workspace = true }

[features]
default = ["std"]
std = [
    "fp-evm/std",
    "frame-support/std",
    "sp-core-hashing/std",
    "sp-std/std",
    "num_enum/std",
]
